// <auto-generated />
using System;
using ITLA_TV.Infraestructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITLA_TV.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250131040811_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITLA_TV.Core.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Generos", (string)null);
                });

            modelBuilder.Entity("ITLA_TV.Core.Domain.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Productoras", (string)null);
                });

            modelBuilder.Entity("ITLA_TV.Core.Domain.Entities.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryGenderId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryGenderId")
                        .HasColumnType("int");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryGenderId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("SecondaryGenderId");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("ITLA_TV.Core.Domain.Entities.Serie", b =>
                {
                    b.HasOne("ITLA_TV.Core.Domain.Entities.Gender", "PrimaryGender")
                        .WithMany("seriesPrimary")
                        .HasForeignKey("PrimaryGenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITLA_TV.Core.Domain.Entities.Producer", "Producer")
                        .WithMany("series")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITLA_TV.Core.Domain.Entities.Gender", "SecondaryGender")
                        .WithMany("seriesSecondary")
                        .HasForeignKey("SecondaryGenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryGender");

                    b.Navigation("Producer");

                    b.Navigation("SecondaryGender");
                });

            modelBuilder.Entity("ITLA_TV.Core.Domain.Entities.Gender", b =>
                {
                    b.Navigation("seriesPrimary");

                    b.Navigation("seriesSecondary");
                });

            modelBuilder.Entity("ITLA_TV.Core.Domain.Entities.Producer", b =>
                {
                    b.Navigation("series");
                });
#pragma warning restore 612, 618
        }
    }
}
